baseURL = 'https://rene-s.github.io/PublicationsList/'
languageCode = 'en-us'
title = 'Publications of Stefanie & Rene Schmidt'
theme = 'no-style-please'

publishDir = "docs"

[params]
  [params.theme_config]
    appearance = "light"