baseURL = '//localhost:1313/'
languageCode = 'en-us'
title = 'Publications of Stefanie & Rene Schmidt'
theme = 'my-no-style-please'

publishDir = "docs"

[params]
  [params.theme_config]
    appearance = "light"